---
abstract: 'functions for controlling whether any scalar variable is read-only'
author:
  - 'Philippe M. Chiasson <gozer@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.113640'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Scalar-Readonly
no_index:
  directory:
    - t
    - inc
requires: {}
version: 0.03
